// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwjyrietntgfzxikjdxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3anlyaWV0bnRnZnp4aWtqZHhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MzIwOTUsImV4cCI6MjA3NDIwODA5NX0.zNNhiW_MTDq5M-Qg24tQ-RzF0Y3kNKlN0jCXk7QvBOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});